export default `import React from 'react'
WITH_STYLES_ADD_IMPORT
WITH_TYPES_ADD_IMPORT

const COMPONENT_NAME = (WITH_TYPES_ADD_DEFINITION): JSX.Element => {
    return <COMPONENT_ELEMENT>COMPONENT_NAME says hi!</COMPONENT_ELEMENT>
}

export default COMPONENT_NAME
`
